#version: '3'

services:  

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.4
#    command: start-single-node --insecure --listen-addr=localhost:26257 --http-addr=localhost:8080
    command: start-single-node --insecure
#    volumes:
#      - "./cockroach-data/cockroachdb:/cockroach/cockroach-data"
    ports:
      - "26257:26257"
      - "8080:8080"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cockroachdb:26257/invoice?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQL95Dialect
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    ports:
      - "8081:8081"
    depends_on:
      - cockroachdb
      - redis
