#version: '3'

services:  

  cockroachdb:
    image: cockroachdb/cockroach:v22.2.4
    container_name: cockroachdb
    hostname: cockroachdb
    command: start-single-node --insecure
    volumes:
      - "./cockroach-data/cockroachdb:/cockroach/cockroach-data"
      - "./scripts:/cockroach/cockroach-data/scripts"
    ports:
      - "26257:26257"
      - "8082:8082"
  setup:
    image: cockroachdb/cockroach:v22.2.4
    command: bash -c "chmod 777 /cockroach-data/scripts/create-db.sh && /cockroach/cockroach-data/scripts/create-db.sh"
    depends_on:
      - cockroachdb
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cockroachdb:26257/invoice?sslmode=disable&user=root&password=
      #&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.PostgreSQL95Dialect
      #SPRING_JPA_DATABASE-PLATFORM: org.hibernate.dialect.CockroachDB201Dialect
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
    ports:
      - "8081:8081"
    depends_on:
      - cockroachdb
      - redis
   